flowchart TD
    %% 사각형 = 상태
    %% 육각형 이벤트 = 화살표 라벨로 표현
    %% 마름모 = 분기

    Start((●)) --> Ready[Ready]

    Ready -- down --> Draw[Draw]
    Draw -- up --> Ready
    Draw -- cancel --> Ready
    Draw -- down --> CheckDraw{"d ≤ 150"}

   

    CheckDraw -- Y --> Cancel((Cancel))
    Cancel --> Pinch[Pinch]
    CheckDraw -- N --> EndDraw((Dispatch Up))
    EndDraw --> Pinch

    Pinch -- cancel --> PinchFinish
    Pinch -- up --> PinchFinish[PinchFinish]
    PinchFinish -- cancel --> EndUndo
    PinchFinish -- up --> CheckUndo{"d ≤ 150"}
    CheckUndo -- Y --> Undo((Undo))
    CheckUndo --> EndUndo(((●)))

    Pinch -- down --> CheckPinchOver{"d ≤ 150"}
    CheckPinchOver -- Y --> PinchOver[PinchOver]
    PinchOver -- cancel --> PinchFinish2
    PinchOver -- up --> PinchFinish2[PinchFinish2]
    PinchFinish2 -- cancel --> PinchFinish3
    PinchFinish2 -- up --> PinchFinish3[PinchFinish3]
    PinchFinish3 -- cancel --> EndRedo
    PinchFinish3 -- up --> CheckRedo{"d ≤ 200"}
    CheckRedo -- Y --> Redo((Redo))
    CheckRedo --> EndRedo(((●)))
