
flowchart TD

    Start((●)) --> Ready[Ready]

    Ready -- down --> Draw[Draw]

    Draw -- up/cancel --> Ready
    Draw -- down --> CheckDraw{"d ≤ 150"}

    CheckDraw -- YES --> DispatchCancel["cancel()"]
    CheckDraw -- NO --> DispatchUp["up()"]

    DispatchUp --> Pinch[Pinch]
    DispatchCancel --> Pinch

    Pinch -- cancel --> EndUndo(((●)))

    Pinch -- up --> CheckPointerCount{"pointerCount == 0"}
    CheckPointerCount -- NO --> Pinch
    CheckPointerCount -- YES --> CheckUndoTime{"d ≤ 150"}

    CheckUndoTime -- NO --> EndUndo
    CheckUndoTime -- YES --> CheckTwoFingerDouble{"d2 ≤ 200"}

    CheckTwoFingerDouble -- YES --> TwoFingerDoubleTap((twoFingerDoubleTap))
    CheckTwoFingerDouble -- NO --> TwoFingerTap((twoFingerTap))

    Pinch -- down --> CheckThreeFinger{"d ≤ 150"}

    CheckThreeFinger -- YES --> ThreeFinger[ThreeFinger]
    CheckThreeFinger -- NO --> CanceledThreeFinger[CanceledThreeFinger]

    ThreeFinger -- cancel --> CanceledThreeFinger

    ThreeFinger -- up --> CheckThreePointerCount{"pointerCount == 0"}
    CheckThreePointerCount -- NO --> ThreeFinger
    CheckThreePointerCount -- YES --> CheckRedoTime{"d ≤ 200"}

    CheckRedoTime -- NO --> EndRedo(((●)))
    CheckRedoTime -- YES --> CheckThreeFingerDouble{"d3 ≤ 200"}

    CheckThreeFingerDouble -- YES --> ThreeFingerDoubleTap((threeFingerDoubleTap))
    CheckThreeFingerDouble -- NO --> ThreeFingerTap((threeFingerTap))

    CanceledThreeFinger -- up/cancel --> EndRedo
